<h3> Get to Know a numpy Array </h3>

You will use the numpy array <code> A</code> for the following 

In [1]:
import numpy as np
A=np.array([[11,12],[21,22],[31,32]])


1) type using the function type 

In [2]:
type(A)

numpy.ndarray

2) the shape of the array 

In [3]:
A.shape

(3, 2)

3) the type of data in the array 

In [4]:
A.dtype

dtype('int32')

4) Find the second row of the numpy array <code>A</code>:

In [5]:
A[1]

array([21, 22])

<h3> Two kinds of Multiplying  </h3>

you will use the following numpy arrays for the next questions 

In [6]:
A=np.array([[11,12],[21,22]])
B=np.array([[1, 0],[0,1]])

1) multiply array <code> A </code> and <code>B</code>

In [7]:
A*B

array([[11,  0],
       [ 0, 22]])

2)  plot the function

In [8]:
np.dot(A,B)
np.dot(B,A)



array([[11, 12],
       [21, 22]])

In [11]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])
A.shape

(4, 2)

In [12]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])

B=np.array([[1,2,3],[4,5,6],[7,8,9]])

np.dot(A,B)

ValueError: shapes (4,2) and (3,3) not aligned: 2 (dim 1) != 3 (dim 0)

<hr>
<small>Copyright &copy; 2018 IBM Cognitive Class. This notebook and its source code are released under the terms of the [MIT License](https://cognitiveclass.ai/mit-license/).</small>